import type { Metadata } from "next";
import "./globals.css";
import Nav from "./components/Nav";
import Fotter from "./components/Fotter";

export const metadata: Metadata = {
  title: "Next Hero Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
        <Fotter />
      </body>
    </html>
  );
}
